package com.example.android.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFFFD166)
val md_theme_light_onPrimary = Color(0xFF1A1A1A)
val md_theme_light_primaryContainer = Color(0xFFFFEAAA)
val md_theme_light_onPrimaryContainer = Color(0xFF1A1A1A)
val md_theme_light_secondary = Color(0xFF1A1A1A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF8C8C8C)
val md_theme_light_onSecondaryContainer = Color(0xFFFFFFFF)
val md_theme_light_tertiary = Color(0xFFC3C3C3)
val md_theme_light_onTertiary = Color(0xFF1A1A1A)
val md_theme_light_tertiaryContainer = Color(0xFFFFF2CC)
val md_theme_light_onTertiaryContainer = Color(0xFF1A1A1A)
val md_theme_light_error = Color(0xFFFF3B3F)
val md_theme_light_errorContainer = Color(0xFFFFE7E8)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF1A1A1A)
val md_theme_light_background = Color(0xFFFFF3E0)
val md_theme_light_onBackground = Color(0xFF1A1A1A)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1A1A1A)
val md_theme_light_surfaceVariant = Color(0xFFEFEFEF)
val md_theme_light_onSurfaceVariant = Color(0xFF1A1A1A)
val md_theme_light_outline = Color(0xFF8C8C8C)
val md_theme_light_inverseOnSurface = Color(0xFFFFD166)
val md_theme_light_inverseSurface = Color(0xFF1A1A1A)
val md_theme_light_inversePrimary = Color(0xFF1A1A1A)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFFFD166)
val md_theme_light_outlineVariant = Color(0xFFB4C4D9)
val md_theme_light_scrim = Color(0x80000000)