package com.example.android.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF2B547E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF6B9ACF)
val md_theme_light_onPrimaryContainer = Color(0xFF000000)
val md_theme_light_secondary = Color(0xFF2E3842)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF99B3D0)
val md_theme_light_onSecondaryContainer = Color(0xFF000000)
val md_theme_light_tertiary = Color(0xFF4B6A88)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBDD8F1)
val md_theme_light_onTertiaryContainer = Color(0xFF000000)
val md_theme_light_error = Color(0xFFD04747)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF0F4F8)
val md_theme_light_onBackground = Color(0xFF1A1C18)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1A1C18)
val md_theme_light_surfaceVariant = Color(0xFFD7E6F5)
val md_theme_light_onSurfaceVariant = Color(0xFF1A1C18)
val md_theme_light_outline = Color(0xFF53697A)
val md_theme_light_inverseOnSurface = Color(0xFF2B547E)
val md_theme_light_inverseSurface = Color(0xFF1A1C18)
val md_theme_light_inversePrimary = Color(0xFF6B9ACF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF2B547E)
val md_theme_light_outlineVariant = Color(0xFFB4C4D9)
val md_theme_light_scrim = Color(0xFF000000)

